[theme]
base = "light"
primaryColor = "
backgroundColor = "
secondaryBackgroundColor = "
textColor = "
linkColor = "
font = "sans-serif"

[theme.sidebar]
backgroundColor = "
secondaryBackgroundColor = "
textColor = "