services:

  kali:
    build:
      context: .
      dockerfile: Dockerfile.attacker
    container_name: attacker
    stdin_open: true
    tty: true
    volumes:
      - ./data:/root/data
    networks:
      - pentest_network
    ports:
      - "55553:55553"

networks:
  pentest_network:
    driver: bridge
